return {
    ['Bard'] = {
        [70] = {
            'Ancient: Call of Power|Anguish Rune Turn In',
            'Arcane Aria|Random Drop',
            'Echoes of the Past|Random Drop',
            'Verse of Veeshan|Random Drop',
            'Voice of the Vampire|Researched or Glowing Rune',
            'Vulka\'s Chant of Flame|Researched or Glowing Rune',
            'Luvwen\'s Aria of Serenity|Researched or Glowing Rune',
        },
        [69] = {
            'Chorus of Life|Researched or Greater Rune',
            'Eriki\'s Psalm of Power|Researched or Greater Rune',
            'Storm Blade|Random Drop',
            'Thousand Blades|Random Drop',
            'Verse of Vesagran|Researched or Greater Rune',
        },
        [68] = {
            'Creeping Dreams|Random Drop',
            'Dirge of Metala|Researched or Muramite Rune',
            'Vulka\'s Chant of Poison|Researched or Muramite Rune',
            'War March of Muram|Researched or Muramite Rune',
            'Yelhun\'s Mystic Call|Researched or Muramite Rune',
        },
        [67] = {
            'Angstlich\'s Wail of Panic|Researched or Lesser Rune',
            'Cantata of Life|Researched or Lesser Rune',
            'Luvwen\'s Lullaby|Researched or Lesser Rune',
            'Vulka\'s Chant of Frost|Researched or Lesser Rune',
            'Zuriki\'s Song of Shenanigans|Researched or Lesser Rune',
        },
        [66] = {
            'Bellow of Chaos|Researched or Minor Rune',
            'Luvwen\'s Aria of Serenity|Researched or Minor Rune',
            'Vulka\'s Chant of DIsease|Researched or Minor Rune',
        },
    },
    ['Beastlord'] = {
        [70] = {
            'Ancient: Savage Ice|Anguish Rune Turn In',
            'Ferocity of Irionu|Researched or Glowing Rune',
            'Festering Malady|Researched or Glowing Rune',
            'Rake|Random Drop',
            'Sha\'s Legacy|Researched or Glowing Rune',
            'Spirit of Oroshar|Random Drop',
            'Spirit of Rashara|Researched or Glowing Rune',
            'Spirit of Sha|Random Drop',
            'Spiritual Rejuvenation|Random Drop',
        },
        [69] = {
            'Empathic Fury|Random Drop',
            'Feral Guard|Researched or Greater Rune',
            'Feral Vigor|Researched or Greater Rune',
            'Glacier Spear|Researched or Greater Rune',
            'Growl of the Panther|Random Drop',
            'Spiritual Ascendance|Researched or Greater Rune',
        },
        [68] = {
            'Growl of the Beast|Researched or Muramite Rune',
            'Reptilian Venom|Random Drop',
            'Spirit of Alladnu|Researched or Muramite Rune',
            'Spirit of Irionu|Researched or Muramite Rune',
        },
        [67] = {
            'Focus of Alladnu|Researched or Lesser Rune',
            'Muada\'s Mending|Researched or Lesser Rune',
            'Spiritual Vitality|Researched or Lesser Rune',
        },
        [66] = {
            'Chimera Blood|Researched or Minor Rune',
            'Healing of MIkkily|Researched or Minor Rune',
        },
    },
    ['Berserker'] = {
        [70] = {
            'Bewildering Scream|Random Drop',
            'Bloodthirst|???',
            'Third Wind|Random Drop',
            'Vengeful Flurry Discipline|Researched or Glowing Rune',
        },
        [69] = {
            'Baffling Strike|Researched or Greater Rune',
            'Destroyer\'s Volley|Random Drop',
        },
        [68] = {
            'Mind Strike|Researched or Muramite Rune',
            'Unflinching Will Discipline|Researched or Muramite Rune',
        },
        [67] = {
            'Crippling Strike|Researched or Lesser Rune',
        },
        [66] = {
            'Axe of the Destroyer|Researched or Minor Rune',
            'Unpredictable Rage Discipline|Researched or Minor Rune',
        },
    },
    ['Cleric'] = {
        [70] = {
            'Ancient: Hallowed Light|Anguish Rune Turn In',
            'Ancient: Pious Conscience|Anguish Rune Turn In',
            'Armor of the Pious|Researched or Glowing Rune',
            'Balikor\'s Mark|Researched or Glowing Rune',
            'Desperate Renewal|Random Drop',
            'Elixir of Divinity|Random Drop',
            'Hand of Conviction|Researched or Glowing Rune',
            'Placate|Researched or Glowing Rune',
            'Puratus|Random Drop',
            'Silent Dictation|Researched or Glowing Rune',
            'Vigilant Condemnation|Random Drop',
        },
        [69] = {
            'Aura of Devotion|Researched or Greater Rune',
            'Calamity|Researched or Greater Rune',
            'Chromastrike|Researched',
            'Mark of the Blameless|Researched or Greater Rune',
            'Ward of Retribution|Random Drop',
            'Word of Vivification|Researched or Minor Rune',
            'Yaulp VII|Researched or Minor Rune',
        },
        [68] = {
            'Death\'s Regret|Researched',
            'Deistic Howl|Random Drop',
            'Desolate Undead|Researched or Muramite Rune',
            'Hammer of Reproach|Researched or Muramite Rune',
            'Pious Light|Researched or Minor Rune',
            'Sound of Divinity|Researched or Minor Rune',
            'UnswerVing Hammer of Retribution|Researched or Minor Rune',
        },
        [67] = {
            'Blessing of Devotion|Researched or Lesser Rune',
            'Conviction|Researched or Lesser Rune',
            'Panoply of Vie|Researched or Lesser Rune',
            'Pious Elixir|Researched or Minor Rune',
            'Reproach|Researched or Minor Rune',
            'Sermon of Reproach|Researched or Minor Rune',
        },
        [66] = {
            'Confidence|Researched or Minor Rune',
            'Pious Remedy|Researched or Minor Rune',
            'Revulsion of Death|Researched or Minor Rune',
            'Shock of Wonder|Researched or Minor Rune',
            'Sun Cloak|Researched or Minor Rune',
            'Symbol of Balikor|Researched or Minor Rune',
            'Ward of Valiance|Researched or Minor Rune',
        },
    },
    ['Druid'] = {
        [70] = {
            'Ancient: Chlorobon|Anguish Rune Turn In',
            'Ancient: Glacier Frost|Anguish Rune Turn In',
            'Barkspur|Random Drop',
            'Blessing of Steeloak|Researched or Glowing Rune',
            'Dawnstrike|Random Drop',
            'Glitterfrost|Researched or Glowing Rune',
            'Hungry Vines|Researched or Glowing Rune',
            'Legacy of Nettles|Researched or Glowing Rune',
            'Mask of the Wild|Researched or Glowing Rune',
            'Moonshadow|Random Drop',
            'Nature Walker\'s Behest|Random Drop',
            'Nature\'s Beckon|Researched or Glowing Rune',
            'Sunburst Blessing|Random Drop',
            'Word of Reconstitution|Random Drop',
        },
        [69] = {
            'Blessing of Oak|Researched or Greater Rune',
            'Oaken Guard|Researched or Greater Rune',
            'Serpent Vines|Random Drop',
            'Solstice Strike|Researched or Greater Rune',
            'Spore Spiral|Random Drop',
            'Vengeance of the Sun|Researched or Greater Rune',
        },
        [68] = {
            'Chlorotrope|Researched or Muramite Rune',
            'Cloak of Nature|Researched or Muramite Rune',
            'Desolate Summoned|Researched or Muramite Rune',
            'Nettlecoat|Researched or Muramite Rune',
            'Skin of the Reptile|Random Drop',
            'Steeloak Skin|Researched or Muramite Rune',
            'Wasp Swarm|Researched or Muramite Rune',
        },
        [67] = {
            'Circle of Sanctum|Random Drop',
            'Glacier Breath|Researched or Lesser Rune',
            'Immolation of the Sun|Researched or Lesser Rune',
            'Lion\'s Strength|Researched or Lesser Rune',
            'Nature\'s Serenity|Researched or Lesser Rune',
            'Nettle Shield|Researched or Lesser Rune',
            'Sun\'s Corona|Researched or Lesser Rune',
        },
        [66] = {
            'Circle of Slaughter|Random Drop',
            'Earth Shiver|Researched or Minor Rune',
            'Instinctual Terror|Researched or Minor Rune',
            'Oaken Vigor|Researched or Minor Rune',
            'Stormwatch|Researched or Minor Rune',
            'Tempest Wind|Researched or Minor Rune',
        },
    },
    ['Enchanter'] = {
        [70] = {
            'Abashi\'s Disempowerment|Random Drop',
            'Ancient: Neurosis|Anguish Rune Turn In',
            'Ancient: Voice of Muram|Anguish Rune Turn In',
            'Chromaburst|Random Drop',
            'Circle of Alendar|Researched or Glowing Rune',
            'Echo of Tashan|Random Drop',
            'Focus Ornate Spellcaster\'s Empowering Essence|Researched',
            'Hastening of Salik|Researched or Glowing Rune',
            'Illusionist\'s Aura|Random Drop',
            'Mind Shatter|Random Drop',
            'True Name|Random Drop',
            'Unified Alacrity|random Drop',
            'Voice of Clairvoyance|Researched or Glowing Rune',
        },
        [69] = {
            'Arcane Noose|Researched or Greater Rune',
            'Color Snap|Researched or Greater Rune',
            'Colored Chaos|Random Drop',
            'Desolate Deeds|Researched or Greater Rune',
            'Euphoria|Researched or Greater Rune',
            'Focus Mass Elaborate Spellcaster\'s Empowering Essence|Researched',
            'Mayhem|Researched or Greater Rune',
            'Rune of Rikkukin|Random Drop',
            'Wake of Felicity|Researched or Greater Rune',
        },
        [68] = {
            'Circle of Dreams|Researched or Muramite Rune',
            'Clairvoyance|Researched or Muramite Rune',
            'Compel|Researched or Muramite Rune',
            'Echoing Madness|Random Drop',
            'Psychosis|Researched or Muramite Rune',
            'Wall of Alendar|Researched or Muramite Rune',
        },
        [67] = {
            'Anxiety Attack|Researched or Lesser Rune',
            'Boon of the Legion|Random Drop',
            'Felicity|Researched or Lesser Rune',
            'Placate|Researched or Lesser Rune',
            'Rune of Salik|Researched or Lesser Rune',
            'Speed of Salik|Researched or Lesser Rune',
        },
        [66] = {
            'Ethereal Rune|Researched or Minor Rune',
            'Mystic Shield|Researched or Minor Rune',
            'Salik\'s Animation|Researched or Minor Rune',
            'Suppression Field|Researched or Minor Rune',
            'Synapsis Spasm|Researched or Minor Rune',
        },
    },
    ['Magician'] = {
        [70] = {
            'Ancient: Nova Strike|Anguish Rune Turn In',
            'Ancient: Veil of Pyrilonus|Anguish Rune Turn In',
            'Call of the Heroes|Random Drop',
            'Child of Earth|Researched or Glowing Rune',
            'Circle of Fireskin|Researched or Glowing Rune',
            'Elemental Simulacrum|Researched or Glowing Rune',
            'Focus Elaborate Spellcaster\'s Empowering Essence|PoK Library',
            'Frantic Flames|Random Drop',
            'Grant Enibik\'s Heirlooms|Random Drop',
            'Grant Spectral Armaments|Random Drop',
            'Iceflame Guard|Random Drop',
            'Raging Servant|Random Drop',
            'Rathe\'s Strength|Random Drop',
            'Shock of Myriad Minions|Researched or Glowing Rune',
            'Spear of Ro|Random Drop',
            'Star Scream|Researched or Glowing Rune',
        },
        [69] = {
            'Bulwark of Calliav|Researched or Greater Rune',
            'Burning Bladegusts|Researched or Greater Rune',
            'Desolate Summoned|Researched or Greater Rune',
            'Elemental Fury|Researched or Greater Rune',
            'Fickle Fire|Random Drop',
            'Focus Mass Intricate Spellcaster\'s Empowering Essence|PoK Library',
            'Renewal of Jerikor|Researched or Greater Rune',
            'Summon: Molten Orb|Random Drop',
        },
        [68] = {
            'Blade Strike|Researched or Muramite Rune',
            'Burning Aura|Random Drop',
            'Child of Fire|Researched or Muramite Rune',
            'Phantom Shield|Researched or Muramite Rune',
            'Pyrilen Skin|Researched or Muramite Rune',
            'Summon Pouch of Jerikor|Researched or Muramite Rune',
        },
        [67] = {
            'Child of Water|Researched or Lesser Rune',
            'Rain of Jerikor|Researched or Lesser Rune',
            'Summon Crystal Belt|Researched or Lesser Rune',
            'Summon Dagger of the Deep|Researched or Lesser Rune',
            'Summon Sphere of Air|Researched or Lesser Rune',
            'Summon Staff of the North Wind|Researched or Lesser Rune',
        },
        [66] = {
            'Bolt of Jerikor|Researched or Minor Rune',
            'Child of Wind|Researched or Minor Rune',
            'Elemental Aura|Researched or Minor Rune',
            'Fireskin|Researched or Minor Rune',
            'Summon Calliav\'s Glowing Bauble|Researched or Minor Rune',
            'Summon Calliav\'s Jeweled Bracelet|Researched or Minor Rune',
            'Summon Calliav\'s Platinum Choker|Researched or Minor Rune',
            'Summon Calliav\'s Runed Mantle|Researched or Minor Rune',
            'Summon Calliav\'s Spiked Ring|Researched or Minor Rune',
            'Summon Calliav\'s Steel Bracelet|Researched or Minor Rune',
            'Summon Fireblade|Researched or Minor Rune',
        },
    },
    ['Monk'] = {
        [70] = {
            'Crystalpalm Discipline|Random Drop',
            'Heel of Kai|Random Drop',
            'Rapid Kick Discipline|Researched or Glowing Rune',
            'Third Wind|Random Drop',
        },
        [69] = {
            'Dragon Fang|Random Drop',
            'Phantom Cry|Researched or Greater Rune',
        },
        [68] = {
            'Counterforce Discipline|Researched or Muramite Rune',
        },
        [67] = {

        },
        [66] = {
            'Dreamwalk Discipline|???',
        },
    },
    ['Necromancer'] = {
        [70] = {
            'Ancient: Allure of Extinction|Anguish Rune Turn In',
            'Ancient: Curse of Mori|Anguish Rune Turn In',
            'Ancient: Touch of Orshilak|Anguish Rune Turn In',
            'Chaos Venom|Researched or Glowing Rune',
            'Dark Assassin|Researched or Glowing Rune',
            'Dark Possession|Researched or Glowing Rune',
            'Death Rune|Random Drop',
            'Desolate Undead|Researched or Glowing Rune',
            'Dread Pyre|Random Drop',
            'Focus Elaborate Spellcaster\'s Empowering Essence|PoK Library',
            'Grave Pact|Random Drop',
            'Word of Chaos|Researched or Glowing Rune',
        },
        [69] = {
            'Bulwark of Calliav|Researched or Greater Rune',
            'Dark Hold|Researched or Greater Rune',
            'Dark Salve|Researched or Greater Rune',
            'Dull Pain|Researched or Greater Rune',
            'Focus Mass Intricate Spellcaster\'s Empowering Essence|PoK Library',
            'Pyre of Mori|Researched or Greater Rune',
            'Shadow Orb|Random Drop',
            'Venom of Anguish|Random Drop',
        },
        [68] = {
            'Call for Blood|Random Drop',
            'Desecrating Darkness|Researched or Muramite Rune',
            'Fang of Death|Researched or Muramite Rune',
            'Scent of Midnight|Researched or Muramite Rune',
            'Shadow of Death|Researched or Muramite Rune',
        },
        [67] = {
            'Dark Nightmare|Researched or Lesser Rune',
            'Glyph of Darkness|Researched or Lesser Rune',
            'Grip of Mori|Researched or Lesser Rune',
            'Lost Soul|Researched or Lesser Rune',
            'Soulspike|Researched or Lesser Rune',
            'Unholy Howl|Researched or Lesser Rune',
        },
        [66] = {
            'Acikin|Researched or Minor Rune',
            'Chaos Plague|Researched or Minor Rune',
            'Eidolon Howl|Researched or Minor Rune',
            'Shadow Guard|Researched or Minor Rune',
        },
    },
    ['Paladin'] = {
        [70] = {
            'Affirmation|Researched or Glowing Rune',
            'Ancient: Force of Jeron|Anguish Rune Turn In',
            'Blessed Aura|Random Drop',
            'Brell\'s Brawny Bulwark|Researched or Glowing Rune',
            'Brell\'s Vibrant Barricade|Random Drop',
            'Hallowforge Discipline|Random Drop',
            'Justice of Marr|Random Drop',
            'Rally|Random Drop',
            'Rampart Discipline|Random Drop',
            'Ward of Tunare|Random Drop',
            'Wave of Piety|Researched or Glowing Rune',
        },
        [69] = {
            'Armor of the Champion|Researched or Greater Rune',
            'Bulwark of Piety|Researched or Greater Rune',
            'Guard of Righteousness|Random Drop',
            'Hand of Direction|Researched or Greater Rune',
            'Pious Cleansing|Researched or Greater Rune',
        },
        [68] = {
            'Jeron\'s Mark|Researched or Muramite Rune',
            'Last Rites|Researched',
            'Light of Piety|Researched or Muramite Rune',
            'Pious Fury|Researched or Muramite Rune',
            'Serene Command|Researched or Muramite Rune',
        },
        [67] = {
            'Crusader\'s Purity|Researched or Lesser Rune',
            'Silvered Fury|Researched or Lesser Rune',
            'Spurn Undead|Researched or Lesser Rune',
            'Symbol of Jeron|Researched or Lesser Rune',
        },
        [66] = {
            'Direction|Researched or Minor Rune',
            'Force of Piety|Researched or Minor Rune',
            'Touch of Piety|Researched or Minor Rune',
        },
    },
    ['Ranger'] = {
        [70] = {
            'Ancient: North Wind|Anguish Rune Turn In',
            'Call of Lightning|Researched or Glowing Rune',
            'Elddar\'s Grasp|Random Drop',
            'Eyes of the Hawk|Random Drop',
            'Onyx Skin|Researched or Glowing Rune',
            'Scorched Earth|Random Drop',
            'Ward of the Hunter|Researched or Glowing Rune',
        },
        [69] = {
            'Earthen Shackles|Random Drop',
            'Focused Hail of Arrows|Random Drop',
            'Hearth Embers|Researched or Greater Rune',
            'Howl of the Predator|Researched or Greater Rune',
            'Nature\'s Balance|Researched or Greater Rune',
            'Nature\'s Denial|Researched or Greater Rune',
            'Bullseye Discipline|Random Drop (Warder\'s Wrath)',
        },
        [68] = {
            'Briarcoat|Researched or Muramite Rune',
            'Frost Wind|Researched or Muramite Rune',
            'Heartslit|Random Drop',
            'Hunter\'s Vigor|Researched or Muramite Rune',
        },
        [67] = {
            'Guard of the Earth|Researched or Lesser Rune',
            'Locust Swarm|Researched or Lesser Rune',
            'Strength of the Hunter|Researched or Lesser Rune',
            'Sylvan Water|Researched or Lesser Rune',
        },
        [66] = {
            'Flame Snap|Researched or Minor Rune',
            'Jolting Snapkicks|Random Drop',
            'Nature Veil|Researched or Minor Rune',
            'Shield of Briar|Researched or Minor Rune',
        },
    },
    ['Rogue'] = {
        [70] = {
            'Assault|Random Drop',
            'Brigand\'s Gaze|Random Drop',
            'Frenzied Stabbing Discipline|Researched or Glowing Rune',
            'Poison Spikes Trap|Random Drop',
            'Razorarc|Random Drop',
            'Third Wind|Random Drop',
        },
        [69] = {
            'Assassin\'s Deceit|???',
            'Assassin\'s Feint|Random Drop',
            'Daggerfall|Researched or Greater Rune',
            'Pinpoint Vulnerability|Random Drop',
        },
        [68] = {
            'Deadly Aim Discipline|Researched or Muramite Rune',
        },
        [67] = {

        },
        [66] = {
            'Imperceptible Discipline|Researched or Minor Rune',
        },
    },
    ['Shadow Knight'] = {
        [70] = {
            'Ancient: Bite of Muram|Anguish Rune Turn In',
            'Cloak of Discord|Researched or Glowing Rune',
            'Decrepit Skin|Random Drop',
            'Rally|PoK Library',
            'Rampart Discipline|Random Drop',
            'Theft of Agony|Random Drop',
            'Theft of Hate|Researched or Glowing Rune',
            'Touch of the Devourer|Researched or Glowing Rune',
            'Voice of Innoruuk|Random Drop',
        },
        [69] = {
            'Dread Gaze|Researched or Greater Rune',
            'Grasp of Lhranc|Random Drop',
            'Pact of Decay|Researched or Greater Rune',
            'Rune of Decay|Researched or Greater Rune',
            'Soul Shield|Random Drop',
            'Spear of Muram|Researched or Greater Rune',
        },
        [68] = {
            'Blood of Inruku|Researched or Muramite Rune',
            'Fickle Shadows|Random Drop',
            'Scythe of Inruku|Researched or Muramite Rune',
            'Son of Decay|Researched or Muramite Rune',
            'Theft of Pain|Researched or Muramite Rune',
        },
        [67] = {
            'Inruku\'s Bite|Researched or Lesser Rune',
            'Shadow Howl|Researched or Lesser Rune',
            'Shroud of Discord|Researched or Lesser Rune',
            'Terror of Discord|Researched or Lesser Rune',
            'Touch of Inruku|Researched or Lesser Rune',
        },
        [66] = {
            'Blood of Discord|Researched or Minor Rune',
            'Bond of Inruku|Researched or Minor Rune',
            'Dark Constriction|Researched or Minor Rune',
            'Soulless Terror|Researched',
        },
    },
    ['Shaman'] = {
        [70] = {
            'Abashi\'s Disempowerment|Random Drop',
            'Ancient: Ancestral Calling|Anguish Rune Turn In',
            'Ancient: Wilslik\'s Mending|Anguish Rune Turn In',
            'Blood of Yoppa|Researched or Glowing Rune',
            'Champion|Researched or Glowing Rune',
            'Commune with the Wild|Random Drop',
            'Frostfall Boon|Random Drop',
            'Ghost of Renewal|Random Drop',
            'Hungry Plague|Random Drop',
            'Idol of Malos|Random Drop',
            'Jinxed Torment|Random Drop',
            'Nectar of Pain|Random Drop',
            'Spiritual Serenity|Researched or Glowing Rune',
            'Talisman of Might|Researched or Glowing Rune',
            'Talisman of the Panther|Random Drop',
            'Talisman of Unification|Random Drop',
            'Talisman of Wunshi|Researched or Glowing Rune',
            'Transcendent Torpor|Random Drop',
            'Vindictive Spirit|Researched or Glowing Rune',
            'Word of Reconstitution|Random Drop',
        },
        [69] = {
            'Balance of Discord|Researched or Greater Rune',
            'Breath of Antraygus|Random Drop',
            'Curse of Sisslak|Researched or Greater Rune',
            'Ice Age|Researched or Greater Rune',
            'Pure Spirit|Researched or Greater Rune',
            'Spirit of the Panther|Random Drop',
            'Talisman of Fortitude|Researched or Greater Rune',
            'Talisman of Perseverance|Researched or Greater Rune',
        },
        [68] = {
            'Lingering Sloth|Random Drop',
            'Pained Memory|Researched or Muramite Rune',
            'Spirit of Fortitude|Researched or Muramite Rune',
            'Talisman of Sense|Researched or Muramite Rune',
            'Wunshi\'s Focusing|Researched or Muramite Rune',
            'Yoppa\'s Mending|Researched or Muramite Rune',
            'Yoppa\'s Rain of Venom|Researched or Muramite Rune',
        },
        [67] = {
            'Ancestral Bulwark|Researched or Lesser Rune',
            'Breath of Wunshi|Researched or Lesser Rune',
            'Farrel\'s Companion|Researched or Lesser Rune',
            'Spirit of Might|Researched or Lesser Rune',
            'Spirit Veil|Researched or Lesser Rune',
        },
        [66] = {
            'Crippling Spasm|Researched or Minor Rune',
            'Putrid Decay|Researched or Minor Rune',
            'Spirit of Perseverance|Researched or Minor Rune',
            'Spirit of Sense|Researched or Minor Rune',
            'Yoppa\'s Spear of Venom|Researched or Minor Rune',
        },
    },
    ['Warrior'] = {
        [70] = {
            'Champion\'s Aura|Random Drop',
            'Flaunt|Random Drop',
            'Shocking Defense Discipline|Researched or Minor Rune',
            'Third Wind|Random Drop',
            'Unyielding Attention|Random Drop',
        },
        [69] = {
            'Throat Jab|Researched or Greater Rune (Bazu Bellow)',
            'Vortex Blade|Random Drop',
        },
        [68] = {
            'Brutal Onslaught Discipline|Researched or Minor Rune',
        },
        [67] = {

        },
        [66] = {
            'Aura of Runes Discipline|Researched or Minor Rune'
        },
    },
    ['Wizard'] = {
        [70] = {
            'Ancient: Core Fire|Anguish Rune Turn In',
            'Ancient: Spear of Gelaqua|Anguish Rune Turn In',
            'Bulwark of Calrena|Researched or Glowing Rune',
            'Chaos Flame|Random Drop',
            'Circle of Thunder|Researched or Glowing Rune',
            'Corona Flare|Researched or Glowing Rune',
            'Ether Flame|Random Drop',
            'Fire Rune|Random Drop',
            'Focus Elaborate Spellcaster\'s Empowering Essence|PoK Library',
            'Gelid Rains|Researched or Glowing Rune',
            'Ice Block|Random Drop',
            'Telakemara|Random Drop',
            'Telekara|Researched or Glowing Rune',
        },
        [69] = {
            'Claw of Vox|Random Drop',
            'Ether Ward|Researched or Greater Rune',
            'Focus Mass Intricate Spellcaster\'s Empowering Essence|PoK Library',
            'Gelidin Comet|Researched or Greater Rune',
            'Mana Weave|Random Drop',
            'Meteor Storm|Researched or Greater Rune',
            'Solist\'s Frozen Sword|Researched or Greater Rune',
            'Spark of Ice|Researched or Greater Rune',
        },
        [68] = {
            'Clinging Frost|Random Drop',
            'Ether Skin|Researched or Muramite Rune',
            'Firebane|Researched or Muramite Rune',
            'Sanctum Portal|Random Drop',
            'Wildmagic Burst|Researched or Muramite Rune',
            'Spark of Thunder|Researched or Muramite Rune',
            'Thundaka|Researched or Muramite Rune',
        },
        [67] = {
            'Circle of Fire|Researched or Lesser Rune',
            'Lightningbane|Researched or Lesser Rune',
            'Phase Walk|Researched or Lesser Rune',
            'Translocate: Slaughter|Quest',
        },
        [66] = {
            'Ether Shield|Researched or Minor Rune',
            'Icebane|Researched or Minor Rune',
            'Spark of Fire|Researched or Minor Rune',
            'Tears of the Sun|Researched or Minor Rune',
        },
    },
}