return {
    ['Bard'] = {
        [70] = {
            "Ancient: Call of Power|Anguish Rune Turn In",
            "Arcane Aria|HC Random Drop",
            "Echoes of the Past|HC Random Drop",
            "Verse of Veeshan|HC Random Drop",
            "Voice of the Vampire|Research/Glowing",
            "Vulka's Chant of Flame|Research/Glowing",
            "Luvwen's Aria of Serenity|Research/Glowing",
        },
        [69] = {
            "Chorus of Life|Research/Greater",
            "Eriki's Psalm of Power|Research/Greater",
            "Storm Blade|HC Random Drop",
            "Thousand Blades|HC Random Drop",
            "Verse of Vesagran|Research/Greater",
        },
        [68] = {
            "Creeping Dreams|HC Random Drop",
            "Dirge of Metala|Research/Muramite",
            "Vulka's Chant of Poison|Research/Muramite",
            "War March of Muram|Research/Muramite",
            "Yelhun's Mystic Call|Research/Muramite",
        },
        [67] = {
            "Angstlich's Wail of Panic|Research/Lesser",
            "Cantata of Life|Research/Lesser",
            "Luvwen's Lullaby|Research/Lesser",
            "Vulka's Chant of Frost|Research/Lesser",
            "Zuriki's Song of Shenanigans|Research/Lesser",
        },
        [66] = {
            "Bellow of Chaos|Research/Minor",
            "Luvwen's Aria of Serenity|Research/Minor",
            "Vulka's Chant of DIsease|Research/Minor",
        },
    },
    ['Beastlord'] = {
        [70] = {
            "Ancient: Savage Ice|Anguish Rune Turn In",
            "Ferocity of Irionu|Research/Glowing",
            "Festering Malady|Research/Glowing",
            "Rake|HC Random Drop",
            "Sha's Legacy|Research/Glowing",
            "Spirit of Oroshar|HC Random Drop",
            "Spirit of Rashara|Research/Glowing",
            "Spirit of Sha|HC Random Drop",
            "Spiritual Rejuvenation|HC Random Drop",
        },
        [69] = {
            "Empathic Fury|HC Random Drop",
            "Feral Guard|Research/Greater",
            "Feral Vigor|Research/Greater",
            "Glacier Spear|Research/Greater",
            "Growl of the Panther|HC Random Drop",
            "Spiritual Ascendance|Research/Greater",
        },
        [68] = {
            "Growl of the Beast|Research/Muramite",
            "Reptilian Venom|HC Random Drop",
            "Spirit of Allandru|Research/Muramite",
            "Spirit of Irionu|Research/Muramite",
        },
        [67] = {
            "Focus of Allandru|Research/Lesser",
            "Muada's Mending|Research/Lesser",
            "Spiritual Vitality|Research/Lesser",
        },
        [66] = {
            "Chimera Blood|Research/Minor",
            "Healing of MIkkily|Research/Minor",
        },
    },
    ['Berserker'] = {
        [70] = {
            "Bewildering Scream|HC Random Drop",
            "Bloodthirst|Researched",
            "Third Wind|HC Random Drop",
            "Vengeful Flurry Discipline|Research/Glowing",
        },
        [69] = {
            "Baffling Strike|Research/Greater",
            "Destroyer's Volley|HC Random Drop",
        },
        [68] = {
            "Mind Strike|Research/Muramite",
            "Unflinching Will|Research/Muramite",
        },
        [67] = {
            "Crippling Strike|Research/Muramite",
        },
        [66] = {
            "Axe of the Destroyer|Research/Minor",
            "Unpredictable Rage Discipline|Research/Minor",
        },
    },
    ['Cleric'] = {
        [70] = {
            "Ancient: Hallowed Light|Anguish Rune Turn In",
            "Ancient: Pious Conscience|Anguish Rune Turn In",
            "Armor of the Pious|Research/Glowing",
            "Balikor's Mark|Research/Glowing",
            "Desperate Renewal|HC Random Drop",
            "Elixir of Divinity|HC Random Drop",
            "Hand of Conviction|Research/Glowing",
            "Placate|Research/Glowing",
            "Puratus|HC Random Drop",
            "Silent Dictation|Research/Glowing",
            "Vigilant Condemnation|HC Random Drop",
        },
        [69] = {
            "Aura of Devotion|Research/Greater",
            "Calamity|Research/Greater",
            "Chromastrike|Researched",
            "Mark of the Blameless|Research/Greater",
            "Ward of Retribution|HC Random Drop",
            "Word of Vivification|Research/Minor",
            "Yaulp VII|Research/Minor",
        },
        [68] = {
            "Death's Regret|Researched",
            "Deistic Howl|HC Random Drop",
            "Desolate Undead|Research/Muramite",
            "Hammer of Reproach|Research/Muramite",
            "Pious Light|Research/Minor",
            "Sound of Divinity|Research/Minor",
            "Unswering Hammer of Retribution|Research/Minor",
        },
        [67] = {
            "Blessing of Devotion|Research/Lesser",
            "Conviction|Research/Lesser",
            "Panoply of Vie|Research/Lesser",
            "Pious Elixir|Research/Minor",
            "Reproach|Research/Minor",
            "Sermon of Reproach|Research/Minor",
        },
        [66] = {
            "Confidence|Research/Minor",
            "Pious Remedy|Research/Minor",
            "Revulsion of Death|Research/Minor",
            "Shock of Wonder|Research/Minor",
            "Sun Cloak|Research/Minor",
            "Symbol of Balikor|Research/Minor",
            "Ward of Valiance|Research/Minor",
        },
    },
    ['Druid'] = {
        [70] = {
            "Ancient: Chlorobon|Anguish Rune Turn In",
            "Ancient: Glacier Frost|Anguish Rune Turn In",
            "Barkspur|HC Random Drop",
            "Blessing of Steeloak|Research/Glowing",
            "Dawnstrike|HC Random Drop",
            "Glitterfrost|Research/Glowing",
            "Hungry Vines|Research/Glowing",
            "Legacy of Nettles|Research/Glowing",
            "Mask of the Wild|Research/Glowing",
            "Moonshadow|HC Random Drop",
            "Nature Walker's Behest|HC Random Drop",
            "Nature's Beckon|Research/Glowing",
            "Sunburst Blessing|HC Random Drop",
            "Word of Reconstitution|HC Random Drop",
        },
        [69] = {
            "Blessing of Oak|Research/Greater",
            "Oaken Guard|Research/Greater",
            "Serpent Vines|HC Random Drop",
            "Solstice Strike|Research/Greater",
            "Spore Spiral|HC Random Drop",
            "Vengeance of the Sun|Research/Greater",
        },
        [68] = {
            "Chlorotrope|Research/Muramite",
            "Cloak of Nature|Research/Muramite",
            "Desolate Summoned|Research/Muramite",
            "Nettlecoat|Research/Muramite",
            "Skin of the Reptile|HC Random Drop",
            "Steeloak Skin|Research/Muramite",
            "Wasp Swarm|Research/Muramite",
        },
        [67] = {
            "Circle of Sanctum|HC Random Drop",
            "Glacier Breath|Research/Lesser",
            "Immolation of the Sun|Research/Lesser",
            "Lion's Strength|Research/Lesser",
            "Nature's Serenity|Research/Lesser",
            "Nettle Shield|Research/Lesser",
            "Sun's Corona|Research/Lesser",
            "Zephyr: Slaughter|Quest",
        },
        [66] = {
            "Circle of Slaughter|HC Random Drop",
            "Earth Shiver|Research/Minor",
            "Instinctual Terror|Research/Minor",
            "Oaken Vigor|Research/Minor",
            "Stormwatch|Research/Minor",
            "Tempest Wind|Research/Minor",
        },
    },
    ['Enchanter'] = {
        [70] = {
            "Abashi's Disempowerment|HC Random Drop",
            "Ancient: Neurosis|Anguish Rune Turn In",
            "Ancient: Voice of Muram|Anguish Rune Turn In",
            "Chromoburst|HC Random Drop",
            "Circle of Alendar|Research/Glowing",
            "Echo of Tashan|HC Random Drop",
            "Focus Ornate Spellcaster's Essence|Researched",
            "Hastening of Salik|Research/Glowing",
            "Illusionist's Aura|HC Random Drop",
            "Mind Shatter|HC Random Drop",
            "True Name|Research/Glowing",
            "Unified Alacrity|HC Random Drop",
            "Voice of Clairvoyance|Research/Glowing",
        },
        [69] = {
            "Arcane Noose|Research/Greater",
            "Color Snap|Research/Greater",
            "Colored Chaos|HC Random Drop",
            "Desolate Deeds|Research/Greater",
            "Euphoria|Research/Greater",
            "Focus Mass Elaborate Spellcaster's Essence|Researched",
            "Mayhem|Research/Greater",
            "Rune of Rikkukin|HC Random Drop",
            "Wake of Felicity|Research/Greater",
        },
        [68] = {
            "Circle of Dreams|Research/Muramite",
            "Clairvoyance|Research/Muramite",
            "Compel|Research/Muramite",
            "Echoing Madness|HC Random Drop",
            "Psychosis|Research/Muramite",
            "Wall of Alendar|Research/Muramite",
        },
        [67] = {
            "Anxiety Attack|Research/Lesser",
            "Boon of the Legion|HC Random Drop",
            "Felicity|Research/Lesser",
            "Placate|Research/Lesser",
            "Rune of Salik|Research/Lesser",
            "Speed of Salik|Research/Lesser",
        },
        [66] = {
            "Ethereal Rune|Research/Minor",
            "Mystic Shield|Research/Minor",
            "Salik's Animation|Research/Minor",
            "Suppression Field|Research/Minor",
            "Synapsis Spasm|Research/Minor",
        },
    },
    ['Magician'] = {
        [70] = {
            "Ancient: Nova Strike|Anguish Rune Turn In",
            "Ancient: Veil of Pyrilonis|Anguish Rune Turn In",
            "Call of the Heroes|HC Random Drop",
            "Child of Earth|Research/Glowing",
            "Circle of Fireskin|Research/Glowing",
            "Elemental Simulacrum|Research/Glowing",
            "Focus Elaborate Spellcaster's Essence|PoK Library",
            "Frantic Flames|HC Random Drop",
            "Grant Enibik's Heirlooms|HC Random Drop",
            "Grant Spectral Armaments|HC Random Drop",
            "Iceflame Guard|HC Random Drop",
            "Raging Servant|HC Random Drop",
            "Rathe's Strength|HC Random Drop",
            "Shock of Myriad Minions|Research/Glowing",
            "Spear of Ro|HC Random Drop",
            "Star Scream|Research/Glowing",
        },
        [69] = {
            "Bulwark of Calliav|Research/Greater",
            "Burning Bladegusts|Research/Greater",
            "Desolate Summoned|Research/Greater",
            "Elemental Fury|Research/Greater",
            "Fickle Fire|HC Random Drop",
            "Focus Mass Intricate Spellcaster's Essence|PoK Library",
            "Renewal of Jerikor|Research/Greater",
            "Summon: Molten Orb|HC Random Drop",
        },
        [68] = {
            "Blade Strike|Research/Muramite",
            "Burning Aura|HC Random Drop",
            "Child of Fire|Research/Muramite",
            "Phantom Shield|Research/Muramite",
            "Pyrilen Skin|Research/Muramite",
            "Summon Pouch of Jerikor|Research/Muramite",
        },
        [67] = {
            "Child of Water|Research/Lesser",
            "Rain of Jerikor|Research/Lesser",
            "Summon Crystal Belt|Research/Lesser",
            "Summon Dagger of the Deep|Research/Lesser",
            "Summon Sphere of Air|Research/Lesser",
            "Summon Staff of the North Wind|Research/Lesser",
        },
        [66] = {
            "Bolt of Jerikor|Research/Minor",
            "Child of Wind|Research/Minor",
            "Elemental Aura|Research/Minor",
            "Fireskin|Research/Minor",
            "Summon Calliav's Glowing Bauble|Research/Minor",
            "Summon Calliav's Jeweled Bracelet|Research/Minor",
            "Summon Calliav's Platinum Choker|Research/Minor",
            "Summon Calliav's Runed Mantle|Research/Minor",
            "Summon Calliav's Spiked Ring|Research/Minor",
            "Summon Calliav's Steel Bracelet|Research/Minor",
            "Summon Fireblade|Research/Minor",
        },
    },
    ['Monk'] = {
        [70] = {
            "Crystalpalm Discipline|HC Random Drop",
            "Heel of Kai|HC Random Drop",
            "Rapid Kick Discipline|Research/Glowing",
            "Third Wind|HC Random Drop",
        },
        [69] = {
            "Dragon Fang|HC Random Drop",
            "Phantom Cry|Research/Greater",
        },
        [68] = {
            "Counterforce Discipline|Research/Muramite",
        },
        [67] = {

        },
        [66] = {
            "Dreamwalk Discipline|Research/Minor",
        },
    },
    ['Necromancer'] = {
        [70] = {
            "Ancient: Allure of Extinction|Anguish Rune Turn In",
            "Ancient: Curse of Mori|Anguish Rune Turn In",
            "Ancient: Touch of Orshilak|Anguish Rune Turn In",
            "Chaos Venom|Research/Glowing",
            "Dark Assassin|Research/Glowing",
            "Dark Possession|Research/Glowing",
            "Death Rune|HC Random Drop",
            "Desolate Undead|Research/Glowing",
            "Dread Pyre|HC Random Drop",
            "Focus Elaborate Spellcaster's Essence|PoK Library",
            "Grave Pact|HC Random Drop",
            "Visceral Vexation|HC Random Drop",
            "Word of Chaos|Research/Glowing",
        },
        [69] = {
            "Bullwark of Calliav|Research/Greater",
            "Dark Hold|Research/Greater",
            "Dark Salve|Research/Greater",
            "Dull Pain|Research/Greater",
            "Focus Mass Intricate Spellcaster's Essence|PoK Library",
            "Pyre of Mori|Research/Greater",
            "Shadow Orb|HC Random Drop",
            "Venom of Anguish|HC Random Drop",
        },
        [68] = {
            "Call for Blood|HC Random Drop",
            "Desecrating Darkness|Research/Muramite",
            "Fang of Death|Research/Muramite",
            "Scent of Midnight|Research/Muramite",
            "Shadow of Death|Research/Muramite",
        },
        [67] = {
            "Dark Nightmare|Research/Lesser",
            "Glyph of Darkness|Research/Lesser",
            "Grip of Mori|Research/Lesser",
            "Lost Soul|Research/Lesser",
            "Soulspike|Research/Lesser",
            "Unholy Howl|Research/Lesser",
        },
        [66] = {
            "Acikin|Research/Minor",
            "Chaos Plague|Research/Minor",
            "Eidolon Howl|Research/Minor",
            "Shadow Guard|Research/Minor",
        },
    },
    ['Paladin'] = {
        [70] = {
            "Affirmation|Research/Glowing",
            "Ancient: Force of Jeron|Anguish Rune Turn In",
            "Blessed Aura|HC Random Drop",
            "Brell's Brawny Bulwark|Research/Glowing",
            "Brell's Vibrant Barricade|HC Random Drop",
            "Hallowforge Discipline|HC Random Drop",
            "Justice of Marr|HC Random Drop",
            "Rally|HC Random Drop",
            "Rampart Discipline|HC Random Drop",
            "Ward of Tunare|HC Random Drop",
            "Wave of Piety|Research/Glowing",
        },
        [69] = {
            "Armor of the Champion|Research/Greater",
            "Bulwark of Piety|Research/Greater",
            "Guard of Righteousness|HC Random Drop",
            "Hand of Direction|Research/Greater",
            "Pious Cleansing|Research/Greater",
        },
        [68] = {
            "Jeron's Mark|Research/Muramite",
            "Last Rites|Researched",
            "Light of Piety|Research/Muramite",
            "Pious Fury|Research/Muramite",
            "Serene Command|Research/Muramite",
        },
        [67] = {
            "Crusader's Purity|Research/Lesser",
            "Silvered Fury|Research/Lesser",
            "Spurn Undead|Research/Lesser",
            "Symbol of Jeron|Research/Lesser",
        },
        [66] = {
            "Direction|Research/Minor",
            "Force of Piety|Research/Minor",
            "Touch of Piety|Research/Minor",
        },
    },
    ['Ranger'] = {
        [70] = {
            "Ancient: North Wind|Anguish Rune Turn In",
            "Call of Lightening|Research/Glowing",
            "Elddar's Grasp|HC Random Drop",
            "Eyes of the Hawk|HC Random Drop",
            "Onyx Skin|Research/Glowing",
            "Scorched Earth|HC Random Drop",
            "Ward of the Hunter|Research/Glowing",
        },
        [69] = {
            "Earthen Shackles|HC Random Drop",
            "Focused Hail of Arrows|HC Random Drop",
            "Hearth Embers|Research/Greater",
            "Howl of the Predator|Research/Greater",
            "Nature's Balance|Research/Greater",
            "Nature's Denial|Research/Greater",
            "Warder's Wrath|HC Random Drop",
        },
        [68] = {
            "Briarcoat|Research/Muramite",
            "Frost Wind|Research/Muramite",
            "Heartslit|HC Random Drop",
            "Hunter's Vigor|Research/Muramite",
        },
        [67] = {
            "Guard of Earth|Research/Lesser",
            "Locust Swarm|Research/Lesser",
            "Strength of the Hunter|Research/Lesser",
            "Sylvan Water|Research/Lesser",
        },
        [66] = {
            "Flame Snap|Research/Minor",
            "Jolting Snapkicks|HC Random Drop",
            "Nature Veil|Research/Minor",
            "Shield of Briar|Research/Minor",
        },
    },
    ['Rogue'] = {
        [70] = {
            "Assault|HC Random Drop",
            "Brigand's Gaze|HC Random Drop",
            "Frenzied Stabbing Discipline|Research/Glowing",
            "Posion Spikes Trap|HC Random Drop",
            "Razorarc|HC Random Drop",
            "Third Wind|HC Random Drop",
        },
        [69] = {
            "Assassin's Deceit|Researched",
            "Assassin's Feint|HC Random Drop",
            "Daggerfall|Research/Greater",
            "Pinpoint Vulnerability|HC Random Drop",
        },
        [68] = {
            "Deadly Aim Discipline|Research/Muramite",
        },
        [67] = {

        },
        [66] = {
            "Imperceptible Discipline|Research/Minor",
        },
    },
    ['Shadow Knight'] = {
        [70] = {
            "Ancient: Bite of Muram|Anguish Rune Turn In",
            "Cloak of Discord|Research/Glowing",
            "Decrepit Skin|HC Random Drop",
            "Rally|PoK Library",
            "Rampart Discipline|HC Random Drop",
            "Theft of Agony|HC Random Drop",
            "Theft of Hate|Research/Glowing",
            "Touch of the Devourer|Research/Glowing",
            "Voice of Innoruuk|HC Random Drop",
        },
        [69] = {
            "Dread Gaze|Research/Greater",
            "Grasp of Lhranc|HC Random Drop",
            "Pact of Decay|Research/Greater",
            "Rune of Decay|Research/Greater",
            "Soul Shield|HC Random Drop",
            "Spear of Muram|Research/Greater",
        },
        [68] = {
            "Blood of Inruku|Research/Muramite",
            "Fickle Shadows|HC Random Drop",
            "Scythe of Inruku|Research/Muramite",
            "Son of Decay|Research/Muramite",
            "Theft of Pain|Research/Muramite",
        },
        [67] = {
            "Inruku's Bite|Research/Lesser",
            "Shadow Howl|Research/Lesser",
            "Shroud of Discord|Research/Lesser",
            "Terror of Discord|Research/Lesser",
            "Touch of Inruku|Research/Lesser",
        },
        [66] = {
            "Blood of Discord|Research/Minor",
            "Bond of Inruku|Research/Minor",
            "Dark Constriction|Research/Minor",
            "Soulless Terror|Researched",
        },
    },
    ['Shaman'] = {
        [70] = {
            "Abashi's Disempowerment|HC Random Drop",
            "Ancient: Ancestral Calling|Anguish Rune Turn In",
            "Ancient: Wilslik's Mending|Anguish Rune Turn In",
            "Blood of Yoppa|Research/Glowing",
            "Champion|Research/Glowing",
            "Commune with the Wild|HC Random Drop",
            "Frostfall Boon|HC Random Drop",
            "Ghost of Renewal|HC Random Drop",
            "Hungry Plague|HC Random Drop",
            "Idol of Malos|HC Random Drop",
            "Jinxed Torment|HC Random Drop",
            "Nectar of Pain|HC Random Drop",
            "Spiritual Serenity|Research/Glowing",
            "Talisman of Might|Research/Glowing",
            "Talisman of the Panther|HC Random Drop",
            "Talisman of Unification|HC Random Drop",
            "Talisman of Wunshi|Research/Glowing",
            "Transcendent Torpor|HC Random Drop",
            "Vindictive Spirit|Research/Glowing",
            "Word of Reconstitution|HC Random Drop",
        },
        [69] = {
            "Balance of Discord|Research/Greater",
            "Breath of Antraygus|HC Random Drop",
            "Curse of Sisslak|Research/Greater",
            "Ice Age|Research/Greater",
            "Pure Spirit|Research/Greater",
            "Spirit of the Panther|HC Random Drop",
            "Talisman of Fortitude|Research/Greater",
            "Talisman of Perseverance|Research/Greater",
        },
        [68] = {
            "Lingering Sloth|HC Random Drop",
            "Pained Memory|Research/Muramite",
            "Spirit of Fortitude|Research/Muramite",
            "Talisman of Sense|Research/Muramite",
            "Wunshi's Focusing|Research/Muramite",
            "Yoppa's Mending|Research/Muramite",
            "Yoppa's Rain of Venom|Research/Muramite",
        },
        [67] = {
            "Ancestral Bulwark|Research/Lesser",
            "Breath of Wunshi|Research/Lesser",
            "Farrel's Companion|Research/Lesser",
            "Spirit of Might|Research/Lesser",
            "Spirit Veil|Research/Lesser",
        },
        [66] = {
            "Crippling Spasm|Research/Minor",
            "Putrid Decay|Research/Minor",
            "Spirit of Perseverance|Research/Minor",
            "Spirit of Sense|Research/Minor",
            "Yoppa's Spear of Venom|Research/Minor",
        },
    },
    ['Warrior'] = {
        [70] = {
            "Champion's Aura|Glowing Rune",
            "Flaunt|HC Random Drop",
            "Shocking Defense Discipline|Research/Minor",
            "Third Wind|HC Random Drop",
            "Unyielding Attention|HC Random Drop",
        },
        [69] = {
            "Throat Jab|Research/Greater",
            "Vortex Blade|HC Random Drop",
        },
        [68] = {
            "Brutal Onslaught Discipline|Research/Minor",
        },
        [67] = {

        },
        [66] = {
            "Aura of Runes Discipline|Research/Minor"
        },
    },
    ['Wizard'] = {
        [70] = {
            "Ancient: Core Fire|Anguish Rune Turn In",
            "Ancient: Spear of Gelaqua|Anguish Rune Turn In",
            "Bulwark of Calrena|Research/Glowing",
            "Chaos Flame|HC Random Drop",
            "Circle of Thunder|Research/Glowing",
            "Corona Flare|Research/Glowing",
            "Ether Flame|HC Random Drop",
            "Fire Rune|HC Random Drop",
            "Focus Elaborate Spellcaster's Essence|PoK Library",
            "Gelid Rains|Research/Glowing",
            "Ice Block|HC Random Drop",
            "Telakemara|HC Random Drop",
            "Telekara|Research/Glowing",
        },
        [69] = {
            "Claw of Vox|HC Random Drop",
            "Ether Ward|Research/Greater",
            "Focus Mass Intricate Spellcaster's Essence|PoK Library",
            "Gelidin Comet|Research/Greater",
            "Mana Weave|HC Random Drop",
            "Meteor Storm|Research/Greater",
            "Solist's Frozen Sword|Research/Greater",
            "Spark of Ice|Research/Greater",
        },
        [68] = {
            "Clinging Frost|HC Random Drop",
            "Ether Skin|Research/Muramite",
            "Firebane|Research/Muramite",
            "Sanctum Portal|HC Random Drop",
            "Wildmagic Burst|Research/Muramite",
            "Spark of Thunder|Research/Muramite",
            "Thundaka|Research/Muramite",
        },
        [67] = {
            "Circle of Fire|Research/Lesser",
            "Lightningbane|Research/Lesser",
            "Phase Walk|Research/Lesser",
            "Translocate: Slaughter|Quest",
        },
        [66] = {
            "Ether Shield|Research/Minor",
            "Icebane|Research/Minor",
            "Spark of Fire|Research/Minor",
            "Tears of the Sun|Research/Minor",
        },
    },
}